=== skrepper/analizetext/AnalizeText1/src/test/resources/func_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://Cyden" 
xmlns="http://Cyden"
elementFormDefault="qualified"
>

<xsd:element name="model" type="ModelType"/>

<xsd:complexType name="ModelType">
  <xsd:sequence>
    <xsd:element name="rules" type="RulesType"/>
    <xsd:element name="approvedFacts" type="ApprovedFactsType"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="RulesType">
  <xsd:sequence>
    <xsd:element name="rule" maxOccurs="unbounded" type="RuleType"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ApprovedFactsType">
  <xsd:sequence>
    <xsd:element name="approvedFact" minOccurs="1" maxOccurs="unbounded" type="factAttrType"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="RuleType">
      <xsd:sequence>
        <xsd:choice>
          <xsd:element name="fact" maxOccurs="1" type="factType"/>
          <xsd:element name="and" maxOccurs="1" type="andType"/>
          <xsd:element name="or" maxOccurs="1" type="orType"/>
        </xsd:choice>  
        <xsd:element name="resultingFact" maxOccurs="1" type="factType"/>
      </xsd:sequence>  
</xsd:complexType>


<!-- Запрет на содержимое: https://www.w3schools.com/xml/schema_complex_empty.asp -->
<xsd:complexType name="factType">
<xsd:attribute name="fact" type="factAttrType"/>
</xsd:complexType>

<xsd:simpleType name="factAttrType">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[_]*[a-zA-Z]+[\w]*"/>
    </xsd:restriction>
</xsd:simpleType>


<xsd:complexType name="andType">
      <xsd:sequence maxOccurs="unbounded">
          <xsd:element name="fact" type="factType" />
      </xsd:sequence>  
</xsd:complexType>

<xsd:complexType name="orType">
      <xsd:sequence>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="fact" type="factType" />
          <xsd:element name="and" type="andType" />
        </xsd:choice>        
      </xsd:sequence>  
</xsd:complexType>

</xsd:schema>

=== skrepper/analizetext/AnalizeText1/src/test/resources/func_xml_1.xml
<?xml version="1.0"?>
<model xmlns="http://Cyden" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://Cyden func_xml.xsd">
  <rules>
    <rule>
      <fact fact="spring"></fact>
      <resultingFact fact="rain111111"></resultingFact>
    </rule>
    <rule>
      <and>
        <fact fact="spring"/>
        <fact fact="winter"/>
      </and>
      <resultingFact fact="autumn"/>
    </rule>
    <rule>
      <or>
        <fact fact="spring1" />
        <fact fact="winter" />
        <and>
          <fact fact="summer"/>
          <fact fact="rain" />
        </and>
      </or>
      <resultingFact fact="autumn"/>
    </rule>
  </rules>
  <approvedFacts>
    <approvedFact>spring</approvedFact>
    <approvedFact>summer</approvedFact>
  </approvedFacts>
</model>
